spring:
  redis:
    database: 1
    host: 192.168.1.25
    port: 6379
    password: 12345678
    timeout: 1000ms
    jedis:
      pool:
        min-idle: 1
        max-idle: 10
        max-active: 20
        max-wait: 1000ms
logging:
  level:
    com.hsy.springboot: debug
#
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://192.168.216.200:3306/uc?useUnicode=true&characterEncoding=UTF-8
#    username: root
#    password: root@mariadb
#
#mybatis:
#  mapper-locations: classpath*:mybatis/*Mapper.xml
#  type-aliases-package: com.hsy.springboot.oauth2.all.bean.entity