

spring:
  redis:
    database: 0
    host: 192.168.216.200
    port: 6379
    password: 123456
    timeout: 1000ms
    jedis:
      pool:
        min-idle: 1
        max-idle: 10
        max-active: 20
        max-wait: 1000ms